name: dtalk

services:
  reverse-proxy:
    image: traefik:v3.1.6
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./traefik-file.yml:/etc/traefik/traefik-file.yml
      - acme:/acme
    env_file:
      - ".env.acme"
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.yourdomain.com`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  api:
    image: "remvn/dtalk:latest"
    restart: unless-stopped
    env_file:
      - ".env"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`{{ .AppDomain }}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.service=api"
      - "traefik.http.services.api.loadbalancer.server.port={{ .AppPort }}"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web:
    image: "remvn/dtalk-web:latest"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`{{ .AppDomain }}`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.service=web"
      - "traefik.http.services.web.loadbalancer.server.port=80"

  # livekit uses some crazy techniques (STUN, TURN, ICE...) to get
  # around NAT, firewalls, ... inorder to get WebRTC to work.
  # You can't try to use it without "network_mode: host" anyway
  # because mapping large range of ports for WebRTC will make Docker freeze
  livekit:
    image: livekit/livekit-server:v1.8
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    network_mode: host
    depends_on:
      - redis
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
    labels:
      - "traefik.enable=false"

  redis:
    image: redis:7-bookworm
    restart: unless-stopped
    command: redis-server /etc/redis.conf
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./redis.conf:/etc/redis.conf

volumes:
  acme:
