log:
  level: INFO

providers:
  docker:
    exposedByDefault: false
  file:
    filename: "/etc/traefik/traefik-file.yml"

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      # tls default config for every router with
      # entrypoint=websecure
      # If there's any user-defined tls labels in docker-compose.yml
      # this default configuration will not apply anything
      # see: https://doc.traefik.io/traefik/routing/entrypoints/#tls
      #
      # tl;dr: just define your domains here and remove all tls labels
      # in docker-compose.yml
      tls:
        certResolver: cloudflare
        domains:
          - main: "{{ .AppDomain }}"
          - main: "{{ .LiveKitDomain }}"
  # webudp:
  #   address: ":443/udp"
  #   udp:
  #     timeout: 10s

api:
  dashboard: false

certificatesResolvers:
  cloudflare:
    acme:
      email: youremail@email.com
      storage: /acme/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory # prod (default)
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging
      dnsChallenge:
        provider: cloudflare
        #disablePropagationCheck: true # uncomment this if you have issues pulling certificates through cloudflare, By setting this flag to true disables the need to wait for the propagation of the TXT record to all authoritative name servers.
        #delayBeforeCheck: 60s # uncomment along with disablePropagationCheck if needed to ensure the TXT record is ready before verification is attempted
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
